version: '3.8'

services:
  backend:
    build:
      context: ./LANFileSharingSystem
    container_name: cdrrmo-backend
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ALLOWED_ORIGINS: "http://localhost:3000,http://192.168.1.84:3000"
      SESSION_KEY: ${SESSION_KEY}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
    volumes:
      - ./LANFileSharingSystem:/app
    working_dir: /app
    command: go run ./cmd/server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cdrrmo-network

  frontend:
    build:
      context: ./my-app
    container_name: cdrrmo-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      REACT_APP_API_BASE: "http://backend:${PORT}"
    networks:
      - cdrrmo-network

  postgres:
    image: postgres:15
    container_name: cdrrmo-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cdrrmo-network

volumes:
  postgres_data:

networks:
  cdrrmo-network:
    driver: bridge
