version: '3.8'

services:
  backend:
    build:
      context: ./LANFileSharingSystem
    container_name: lanfilesharing-backend
    ports:
      - "${PORT}:${PORT}"  # use from .env
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - lan-network

  frontend:
    build:
      context: ./my-app
    container_name: lanfilesharing-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - lan-network

  db:
    image: postgres:14-alpine
    container_name: lanfilesharing-db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lan-network

volumes:
  pgdata:

networks:
  lan-network:
    driver: bridge
